#!/bin/bash

# Variables Definition
edp=eDP-1
hdmi=HDMI-1
#lid=$(/bin/cat /proc/acpi/button/lid/LID0/state | awk {'print $2'})
#connected=$(xrandr --query | grep $hdmi | awk {'print $2'})

# Workspaces Config
	bspc monitor $edp -d 1 2 3 4 5
	bspc monitor $hdmi -d 1 2 3 4 5

# Border and Gaps
bspc config border_width        1
bspc config window_gap          15
bspc config top_padding			20

# Coloring
bspc config focused_border_color "#98C379"

# Config
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Window Rules
bspc rule -a *:*:'Picture-in-picture' state=floating sticky=on follow=off focus=on

# Autostart programs
/usr/libexec/polkit-gnome-authentication-agent-1 &
systemctl --user stop plasma-kglobalaccel.service &
pgrep -x sxhkd > /dev/null || sxhkd &
pkill dunst ; dunst &
pkill picom ; picom -f &
nitrogen --restore &

~/.config/polybar/launch.sh

# Dualmonitor
#monitor_setup
dualmonitor
